In [18]:
# 导入相应模块
from sklearn.linear_model import LogisticRegression # 逻辑回归算法
from sklearn.model_selection import train_test_split # 用于交叉验证数据拆分
from sklearn.metrics import classification_report #模型评估

In [19]:
# 导入数据预处理函数
%run 03-数据预处理函数.ipynb

In [20]:
# step-1：数据预处理
TrainData = prepare_data("datasets/titanic/train.csv","train")
TrainData.head()

,Survived,AgeIsMissing,IsAlone,IsMother,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,...,"SexAgeCombo_female_(0, 18]","SexAgeCombo_female_(18, 25]","SexAgeCombo_female_(25, 40]","SexAgeCombo_female_(40, 60]","SexAgeCombo_female_(60, 100]","SexAgeCombo_male_(0, 18]","SexAgeCombo_male_(18, 25]","SexAgeCombo_male_(25, 40]","SexAgeCombo_male_(40, 60]","SexAgeCombo_male_(60, 100]"
0,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1,1,0,0,0,1,0,0,1,0,1,...,0,0,1,0,0,0,0,0,0,0
2,1,0,1,0,0,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [21]:
TrainData.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Survived,891.0,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
AgeIsMissing,891.0,0.198653,0.399210,0.0,0.0,0.0,0.0,1.0
IsAlone,891.0,0.602694,0.489615,0.0,0.0,1.0,1.0,1.0
IsMother,891.0,0.084175,0.277806,0.0,0.0,0.0,0.0,1.0
Pclass_1,891.0,0.242424,0.428790,0.0,0.0,0.0,0.0,1.0
Pclass_2,891.0,0.206510,0.405028,0.0,0.0,0.0,0.0,1.0
Pclass_3,891.0,0.551066,0.497665,0.0,0.0,1.0,1.0,1.0
Sex_female,891.0,0.352413,0.477990,0.0,0.0,0.0,1.0,1.0
Sex_male,891.0,0.647587,0.477990,0.0,0.0,1.0,1.0,1.0
Embarked_C,891.0,0.188552,0.391372,0.0,0.0,0.0,0.0,1.0
Embarked_Q,891.0,0.086420,0.281141,0.0,0.0,0.0,0.0,1.0
Embarked_S,891.0,0.725028,0.446751,0.0,0.0,1.0,1.0,1.0
"AgeBin_(0, 18]",891.0,0.156004,0.363063,0.0,0.0,0.0,0.0,1.0
"AgeBin_(18, 25]",891.0,0.181818,0.385911,0.0,0.0,0.0,0.0,1.0
"AgeBin_(25, 40]",891.0,0.493827,0.500243,0.0,0.0,0.0,1.0,1.0
"AgeBin_(40, 60]",891.0,0.143659,0.350940,0.0,0.0,0.0,0.0,1.0
"AgeBin_(60, 100]",891.0,0.024691,0.155270,0.0,0.0,0.0,0.0,1.0
"FareBin_(-0.001, 7.854]",891.0,0.200898,0.400897,0.0,0.0,0.0,0.0,1.0
"FareBin_(7.854, 10.5]",891.0,0.206510,0.405028,0.0,0.0,0.0,0.0,1.0
"FareBin_(10.5, 21.679]",891.0,0.193042,0.394907,0.0,0.0,0.0,0.0,1.0
"FareBin_(21.679, 39.688]",891.0,0.202020,0.401733,0.0,0.0,0.0,0.0,1.0
"FareBin_(39.688, 512.329]",891.0,0.197531,0.398360,0.0,0.0,0.0,0.0,1.0
FamilySize_1,891.0,0.602694,0.489615,0.0,0.0,1.0,1.0,1.0
FamilySize_2,891.0,0.180696,0.384982,0.0,0.0,0.0,0.0,1.0
FamilySize_3,891.0,0.114478,0.318570,0.0,0.0,0.0,0.0,1.0
FamilySize_4,891.0,0.032548,0.177549,0.0,0.0,0.0,0.0,1.0
FamilySize_5,891.0,0.016835,0.128725,0.0,0.0,0.0,0.0,1.0
FamilySize_6,891.0,0.024691,0.155270,0.0,0.0,0.0,0.0,1.0
FamilySize_7,891.0,0.013468,0.115332,0.0,0.0,0.0,0.0,1.0
FamilySize_8,891.0,0.006734,0.081830,0.0,0.0,0.0,0.0,1.0
FamilySize_11,891.0,0.007856,0.088337,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(0, 18]",891.0,0.076319,0.265657,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(18, 25]",891.0,0.060606,0.238740,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(25, 40]",891.0,0.161616,0.368305,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(40, 60]",891.0,0.050505,0.219108,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(60, 100]",891.0,0.003367,0.057961,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(0, 18]",891.0,0.079686,0.270958,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(18, 25]",891.0,0.121212,0.326557,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(25, 40]",891.0,0.332211,0.471271,0.0,0.0,0.0,1.0,1.0
"SexAgeCombo_male_(40, 60]",891.0,0.093154,0.290811,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(60, 100]",891.0,0.021324,0.144544,0.0,0.0,0.0,0.0,1.0

In [22]:
# step2：模型训练

# 拆分特征根与目标变量
trainData_X = TrainData.drop(['Survived'], axis = 1)
trainData_y = TrainData.Survived 

# 拆分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(trainData_X, trainData_y, test_size=0.3, random_state=123456)

# 模型实例化
lr = LogisticRegression()

# 训练模型
lr.fit(X_train, y_train)

# step3：模型评估
# 对剩余的30%数据样本做预测
y_test_pred = lr.predict(X_test)
# 比较预测值与真实值
print(classification_report(y_test,y_test_pred))

             precision    recall  f1-score   support

          0       0.82      0.81      0.81       166
          1       0.70      0.72      0.71       102

avg / total       0.77      0.77      0.77       268

In [23]:
# 处理新数据样本
TestData = prepare_data("datasets/titanic/test.csv","test")
# 准备测试集，不需要ID
Test_X = TestData.drop(['PassengerId'], axis = 1)
# 对测试数据进行预测
pred = lr.predict(Test_X)
# 生成最终提交结果Submission 
Submission = pd.DataFrame({'PassengerId':TestData.PassengerId,'Survived':pred})
# 导出为csv文件
Submission.to_csv("./datasets/titanic/Submission.csv", index=False)
# 查看导出文件，读取测试结果数据集
submission_df = pd.read_csv('./datasets/titanic/Submission.csv')
submission_df.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [24]:
import numpy as np
# 把变量名称和系数对应起来组合成dataframe
coef = pd.DataFrame(list(zip(X_train.columns, np.transpose(lr.coef_))), columns=['columns', 'coef'])
# 按照coef的值从高到底排序
coef = coef.sort_values(by =['coef'], ascending=False)
coef

                         columns                    coef
6                     Sex_female    [1.1855087706643865]
23                  FamilySize_3    [0.9953615475622508]
3                       Pclass_1    [0.9417968919554628]
24                  FamilySize_4    [0.7997045141211578]
35      SexAgeCombo_male_(0, 18]    [0.6634546413355232]
27                  FamilySize_7    [0.6261636581943099]
31   SexAgeCombo_female_(18, 25]    [0.5124758743632266]
11                AgeBin_(0, 18]    [0.4660995597380431]
33   SexAgeCombo_female_(40, 60]    [0.3775782966402478]
20     FareBin_(39.688, 512.329]    [0.3650118302476524]
22                  FamilySize_2   [0.34522585294467567]
1                        IsAlone   [0.33252250576501347]
21                  FamilySize_1   [0.33252250576501347]
32   SexAgeCombo_female_(25, 40]    [0.3238920732535494]
34  SexAgeCombo_female_(60, 100]   [0.16891760800483394]
18        FareBin_(10.5, 21.679]   [0.16827814587391873]
19      FareBin_(21.679, 39.688]   [0.15535304497742197]
9                     Embarked_Q   [0.14684955456508672]
8                     Embarked_C    [0.1350761121611938]
0                   AgeIsMissing   [0.02634230995282687]
13               AgeBin_(25, 40]   [0.01684141008770678]
12               AgeBin_(18, 25]  [-0.02345967836583299]
30    SexAgeCombo_female_(0, 18]  [-0.19735508159747758]
17         FareBin_(7.854, 10.5]   [-0.2008752097984517]
4                       Pclass_2  [-0.21038318919132715]
15              AgeBin_(60, 100]   [-0.2714008509032758]
14               AgeBin_(40, 60]  [-0.30207496136696443]
37     SexAgeCombo_male_(25, 40]   [-0.3070506631658439]
10                    Embarked_S  [-0.39592018753666436]
39    SexAgeCombo_male_(60, 100]  [-0.44031845890810967]
36     SexAgeCombo_male_(18, 25]     [-0.53593555272905]
16       FareBin_(-0.001, 7.854]   [-0.6017623321108705]
2                       IsMother   [-0.6132344454738499]
38     SexAgeCombo_male_(40, 60]   [-0.6796532580072129]
29                 FamilySize_11   [-0.7332362479427194]
26                  FamilySize_6   [-0.7702175959551041]
28                  FamilySize_8   [-0.7874404247607103]
5                       Pclass_3   [-0.8454082235744587]
25                  FamilySize_5   [-0.9220783307392215]
7                       Sex_male   [-1.2995032914747329]

In [25]:
# 模型保存
import pickle
with open('lrmodel.pickle', 'wb') as fw:
    pickle.dump(lr, fw)

In [26]:
# 模型加载
with open('lrmodel.pickle', 'rb') as fr:
    new_lr = pickle.load(fr)
new_lr.predict(X_test)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1], dtype=int64)