In [1]:
# 导入相关包
import pandas as pd
# 读取数据
titanic_df = pd.read_csv('./datasets/titanic/train.csv')
# drop 掉 PassengerId,Name,Ticket,Cabin
titanic_df = titanic_df.drop(['PassengerId','Name','Ticket','Cabin'], axis = 1)
# 构造一个新变量 AgeIsMissing
titanic_df['AgeIsMissing'] = 0
titanic_df.loc[titanic_df['Age'].isnull(), 'AgeIsMissing'] = 1
# 对 Age 缺失值进行均值填充
age_mean = round(titanic_df['Age'].mean())
titanic_df['Age'].fillna(age_mean, inplace=True)
# 对 Embarked 缺失值用'S'替换
titanic_df['Embarked'].fillna('S', inplace=True)
# 对 Age 进行分箱--自定义分箱
cut_points = [0,18,25,40,60,100]
titanic_df["AgeBin"] = pd.cut(titanic_df.Age, bins=cut_points)
# 对 Fare 船票价格进行分箱--等深分箱
titanic_df["FareBin"] = pd.qcut(titanic_df.Fare, 5)
# 构造 FamilySize 变量
titanic_df['FamilySize'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
# 构造一个新变量 IsAlone（是否独自一人)
titanic_df['IsAlone'] = 0
titanic_df.loc[titanic_df['FamilySize'] == 1, 'IsAlone'] = 1
# 构造一个新变量 IsMother（是否是母亲）
titanic_df['IsMother'] = 0
titanic_df.loc[(titanic_df['Sex']=='female') & (titanic_df['Parch']>0) & (titanic_df['Age']>20),
'IsMother'] = 1
# 把 Sex 性别和 AgeBin 特征进行组合
titanic_df['SexAgeCombo'] = titanic_df['Sex'] + "_" + titanic_df['AgeBin'].astype(str)
# 对 Pclass,Sex,Embarked,AgeBin,FareBin,FamilySize,Sex_Age_combo 进行独热编码
Pclass = pd.get_dummies(titanic_df.Pclass,prefix='Pclass')
Sex = pd.get_dummies(titanic_df.Sex,prefix='Sex')
Embarked = pd.get_dummies(titanic_df.Embarked,prefix='Embarked')
AgeBin = pd.get_dummies(titanic_df.AgeBin,prefix='AgeBin')
FareBin = pd.get_dummies(titanic_df.FareBin,prefix='FareBin')
FamilySize = pd.get_dummies(titanic_df.FamilySize,prefix='FamilySize')
SexAgeCombo = pd.get_dummies(titanic_df.SexAgeCombo,prefix='SexAgeCombo')
# 把需要的变量全部拼接在一起 
TrainData =pd.concat([titanic_df[['Survived','AgeIsMissing','IsAlone','IsMother']],
Pclass,Sex,Embarked,AgeBin,FareBin,FamilySize,SexAgeCombo],axis=1)
# 描述性统计
TrainData.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Survived,891.0,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
AgeIsMissing,891.0,0.198653,0.399210,0.0,0.0,0.0,0.0,1.0
IsAlone,891.0,0.602694,0.489615,0.0,0.0,1.0,1.0,1.0
IsMother,891.0,0.084175,0.277806,0.0,0.0,0.0,0.0,1.0
Pclass_1,891.0,0.242424,0.428790,0.0,0.0,0.0,0.0,1.0
Pclass_2,891.0,0.206510,0.405028,0.0,0.0,0.0,0.0,1.0
Pclass_3,891.0,0.551066,0.497665,0.0,0.0,1.0,1.0,1.0
Sex_female,891.0,0.352413,0.477990,0.0,0.0,0.0,1.0,1.0
Sex_male,891.0,0.647587,0.477990,0.0,0.0,1.0,1.0,1.0
Embarked_C,891.0,0.188552,0.391372,0.0,0.0,0.0,0.0,1.0
Embarked_Q,891.0,0.086420,0.281141,0.0,0.0,0.0,0.0,1.0
Embarked_S,891.0,0.725028,0.446751,0.0,0.0,1.0,1.0,1.0
"AgeBin_(0, 18]",891.0,0.156004,0.363063,0.0,0.0,0.0,0.0,1.0
"AgeBin_(18, 25]",891.0,0.181818,0.385911,0.0,0.0,0.0,0.0,1.0
"AgeBin_(25, 40]",891.0,0.493827,0.500243,0.0,0.0,0.0,1.0,1.0
"AgeBin_(40, 60]",891.0,0.143659,0.350940,0.0,0.0,0.0,0.0,1.0
"AgeBin_(60, 100]",891.0,0.024691,0.155270,0.0,0.0,0.0,0.0,1.0
"FareBin_(-0.001, 7.854]",891.0,0.200898,0.400897,0.0,0.0,0.0,0.0,1.0
"FareBin_(7.854, 10.5]",891.0,0.206510,0.405028,0.0,0.0,0.0,0.0,1.0
"FareBin_(10.5, 21.679]",891.0,0.193042,0.394907,0.0,0.0,0.0,0.0,1.0
"FareBin_(21.679, 39.688]",891.0,0.202020,0.401733,0.0,0.0,0.0,0.0,1.0
"FareBin_(39.688, 512.329]",891.0,0.197531,0.398360,0.0,0.0,0.0,0.0,1.0
FamilySize_1,891.0,0.602694,0.489615,0.0,0.0,1.0,1.0,1.0
FamilySize_2,891.0,0.180696,0.384982,0.0,0.0,0.0,0.0,1.0
FamilySize_3,891.0,0.114478,0.318570,0.0,0.0,0.0,0.0,1.0
FamilySize_4,891.0,0.032548,0.177549,0.0,0.0,0.0,0.0,1.0
FamilySize_5,891.0,0.016835,0.128725,0.0,0.0,0.0,0.0,1.0
FamilySize_6,891.0,0.024691,0.155270,0.0,0.0,0.0,0.0,1.0
FamilySize_7,891.0,0.013468,0.115332,0.0,0.0,0.0,0.0,1.0
FamilySize_8,891.0,0.006734,0.081830,0.0,0.0,0.0,0.0,1.0
FamilySize_11,891.0,0.007856,0.088337,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(0, 18]",891.0,0.076319,0.265657,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(18, 25]",891.0,0.060606,0.238740,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(25, 40]",891.0,0.161616,0.368305,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(40, 60]",891.0,0.050505,0.219108,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_female_(60, 100]",891.0,0.003367,0.057961,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(0, 18]",891.0,0.079686,0.270958,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(18, 25]",891.0,0.121212,0.326557,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(25, 40]",891.0,0.332211,0.471271,0.0,0.0,0.0,1.0,1.0
"SexAgeCombo_male_(40, 60]",891.0,0.093154,0.290811,0.0,0.0,0.0,0.0,1.0
"SexAgeCombo_male_(60, 100]",891.0,0.021324,0.144544,0.0,0.0,0.0,0.0,1.0